stages:
  - build
  - deploy

build:
  image: docker:latest
  services:
    - docker:dind
  tags:
    - meedan
    - meedan-labs
  stage: build
  variables:
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  script:
    - apk add --no-cache curl jq python py-pip git
    - git clone https://${GITHUB_TOKEN}:x-oauth-basic@github.com/meedan/configurator ./configurator
    - d=configurator/check/live/cc/; for f in $(find $d -type f); do cp "$f" "${f/$d/}"; done
    - pip install docutils==0.14
    - pip install awscli==1.16.201
    - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -f Dockerfile -t "$ECR_BASE_URL:$CI_COMMIT_SHA"  .
    - docker push "$ECR_BASE_URL:$CI_COMMIT_SHA"
  only:
    - master

deploy:
  image: python:3-alpine
  stage: deploy
  tags:
    - meedan
    - meedan-labs
  variables:
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
  script:
    - pip install ecs-deploy==1.7.0
    - ecs deploy ecs-live  live-cc-deville --image live-cc-deville-c $ECR_BASE_URL:$CI_COMMIT_SHA --timeout 3600
    - echo "new Image was deployed $ECR_BASE_URL:$CI_COMMIT_SHA"
  only:
    - master